### ISSUE TITLE
The "max-body" value set in .edgerc is not honored

### ISSUE THREAD

**Issue by maglietti** [akamai-open/AkamaiOPEN-edgegrid-python#18] opened 2015-07-29 01:25 UTC
The `max-body` value is hard coded to `2048` in both `edgerc.py` and `edgegrid.py`. Please update the library to honor the `max-body` value set in `.edgerc`. 

This is causing issues with large POST bodies like the ones seen when using the config-dns OPEN API.

**Comment by jjjhhhlll** [comment] 2015-07-29 13:38
it is spelled 'max_body' for this library.  I think that's the cause.  All the other parameters use '_'.  I think I tried to make them all consistent.

see:

https://github.com/akamai-open/AkamaiOPEN-edgegrid-python/blob/master/akamai/edgegrid/edgerc.py#L36

and

https://github.com/akamai-open/AkamaiOPEN-edgegrid-python/blob/master/akamai/edgegrid/test/sample_edgerc

**Comment by jjjhhhlll** [comment] 2015-07-29 15:00
fixed in https://github.com/akamai-open/AkamaiOPEN-edgegrid-python/pull/19

**Closed by jjjhhhlll** 2015-07-29 15:00 UTC
